language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
script:
  - go test -v -cover -race -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
branches:
  only:
  - master
